apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quiz-argo-applicatiion
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/FegrusB/quiz-kubernetes
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true