apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-sb-server-deployment
  labels:
    app: quiz-sb-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quiz-sb-server
  template:
    metadata:
      labels:
        app: quiz-sb-server
    spec:
      containers:
        - image: fegrus/quiz-sb-server
          name: sb-server
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: db-url
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: db-db-name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: sb-service
spec:
  selector:
    app: quiz-sb-server
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sb-server-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sb-service
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  sb-server-https
  annotations:
    cert-manager.io/issuer: letsencrypt-production
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: quiz.myquizapp.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sb-service
                port:
                  number: 8080
  tls:
    - hosts:
        - quiz.myquizapp.co.uk # Change by your domain
      secretName: myquizapp-co-uk-tls
