apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: quiz-secrets
  namespace: default
spec:
  appName: quiz-secrets
  destination:
    create: true
    labels:
      hvs: "true"
    name: quiz-secrets
    namespace: default
  refreshAfter: 1h